[#9] 드롭다운 컴포넌트
codeit-team8/rolling pull request #32
Opened 2023-11-08 05:26 UTC by hyeyoonS

## 관련 이슈
#9

## 구현 기능 및 변경 사항

드롭다운 컴포넌트 생성했습니다. 

## 스크린샷(선택)
![2023-11-08 14;09;07](https://github.com/codeit-team8/rolling/assets/144667455/60a8a4ee-7f62-46c7-b2a4-c3283c3b929e)

2023-11-08 05:33 UTC, BeMatthewsong reviewed
테스트 파일 코드랑 px를 rem,으로 바꿔주시면 좋을듯해요!

2023-11-08 05:33 UTC, BeMatthewsong commented on src/App.jsx
> +>>>>>>> e91573370556477179ca1821b21b9c485f605ba1
테스트 파일 지워주세요~

2023-11-08 05:33 UTC, BeMatthewsong commented on src/components/DropDown/DropDown.jsx
> +  font-size: 16px;
px에서 rem으로 바꿔주세요

ex. 320px -> 32rem (저희는 10px이 기준이에요)

2023-11-08 05:33 UTC, BeMatthewsong commented on src/components/DropDown/DropDown.jsx
> +    $isActive ? `outline: 2px solid var(--gray-500, #555);` : `outline: 1px solid var(--gray-500, #555);`}
good

2023-11-08 05:33 UTC, BeMatthewsong commented on src/components/DropDown/DropDown.jsx
> +  font-size: 16px;
px 있는 부분 바꿔주세요 
border-radius 빼고요!

2023-11-08 05:33 UTC, BeMatthewsong commented on src/components/DropDown/DropDown.jsx
> +        </DropDownContentsWrapper>
이미지랑 선택된 값이 있는 영역이랑 분리해서 말해주신 틈을 만드셨네요!

2023-11-08 05:35 UTC, gooma519 requested changes
conflict 해결하시고 민혁님 말씀처럼 단위만 바꿔주시면 될 것 같아요

2023-11-08 05:35 UTC, gooma519 commented on src/App.jsx
> +=======
conflict 해결하셔야 할 것 같아요

2023-11-08 05:37 UTC, kses1010 requested changes
고생하셨습니다. 엄청 고생한 모습이 보였네요.

다만, git conflict는 꼭 해결해주시고, 추가적으로 메소드 추출, option 리스트를 만들어서 prop으로 따로 분리할 수 있도록 하면 좋을듯 합니다

2023-11-08 05:37 UTC, kses1010 commented on src/App.jsx
> +>>>>>>> e91573370556477179ca1821b21b9c485f605ba1
git conflict 해결하시고 커밋하시면 됩니다.

2023-11-08 05:37 UTC, kses1010 commented on src/components/DropDown/DropDown.jsx
> +function DropDown() {
DropDown -> Dropdown으로 한단어일거에요 중간에 대문자 없애주시고 파일과 폴더 이름도 변경해주시면 됩니다.

2023-11-08 05:37 UTC, kses1010 commented on src/components/DropDown/DropDown.jsx
> +const options = ['옵션예시1번', '옵션예시2번', '옵션예시3번', '옵션예시4번'];
여기서 옵션이 상대와의 관계, 폰트 선택인데 두 개의 배열을 만들고 그 배열의 키를 의미하는 prop을 받아 처리하도록 하면 될듯 합니다.

2023-11-08 05:37 UTC, kses1010 commented on src/components/DropDown/DropDown.jsx
> +      <DropDownBtn $isActive={isActive} onClick={() => setIsActive((prev) => !prev)}>
여기 핸들러 메소드는 메소드 추출하여 따로 적어주실 수 있을까요? 한눈에 알기 어려워서 추출하면 좋을 듯 ㅎ바니다.

2023-11-08 05:37 UTC, kses1010 commented on src/components/DropDown/DropDown.jsx
> +              }}
여기도 마찬가지로 메서드 추출하시고 메소드를 넣어주는 방법을 하시면 좋을듯 합니다.

2023-11-08 05:37 UTC, kses1010 commented on src/components/DropDown/DropDown.jsx
> +`;
저희가 의논한대로 감싸는 컴포넌트는 컴포넌트 이름 + container라고 지으면 됩니다.
즉 여기는
```suggestion
const DropdownContainer = styled.div`
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
`;
```

2023-11-08 05:37 UTC, kses1010 commented on src/components/DropDown/DropDown.jsx
> +`;
로 해주시면 좋을듯 합니다.

2023-11-08 05:37 UTC, kses1010 commented on src/components/DropDown/DropDown.jsx
> +  font-size: 16px;
여기도 마찬가지로 px 보다는 rem으로 바꾸시고 border-radius나 border경우에는 px로 하셔도 됩니다.

2023-11-08 05:37 UTC, kses1010 commented on src/components/DropDown/DropDown.jsx
> +  padding: 10px 0;
여기도 마찬가지로 rem으로 바꿔주세요

2023-11-08 05:37 UTC, kses1010 commented on src/components/DropDown/DropDown.jsx
> +  box-shadow: 0px 2px 12px 0px rgba(0, 0, 0, 0.08);
가능하다면 0px보다는 0으로 해주시면됩니다.

2023-11-08 05:37 UTC, kses1010 commented on src/components/DropDown/DropDown.jsx
> +  font-size: 16px;
여기도 마찬가지로 px -> rem으로 바꿔주세요

2023-11-08 05:37 UTC, kses1010 commented on src/components/DropDown/DropDown.jsx
> +    $isActive ? `outline: 2px solid var(--gray-500, #555);` : `outline: 1px solid var(--gray-500, #555);`}
이 코드가 선택사항일 때 발생하는 border 색깔이군요

2023-11-08 12:03 UTC, BeMatthewsong approved these changes
LGTM

2023-11-09 00:46 UTC, kses1010 approved these changes
LGTM!

2023-11-09 00:47 UTC, gooma519 approved these changes

2023-11-09 00:48 UTC, merged