[#35] 옵션 컴포넌트
codeit-team8/rolling pull request #52
Opened 2023-11-10 07:01 UTC by hyeyoonS

## 관련 이슈
#35

## 구현 기능 및 변경 사항
- 옵션 버튼에서 선택하면 테두리랑 글씨에 색 입히기
- 디폴트 이미지 체크 하기

수정이 필요할 것 같아서 주석 등을 제거하지 않고 우선 올립니다...! CSS속성은 수정이 완료된 후 별도로 파일 분리하겠습니다.
검토가 요청 드리는 부분들은 코멘트로 달겠습니다. 

1) 우선 옵션을 선택하는 버튼중에서 이미지 버튼을 클릭하면  아래의 메시지가 뜹니다.. 

![image](https://github.com/codeit-team8/rolling/assets/144667455/ca940034-7598-4e8f-a884-077de5c9564b)

## 스크린샷

![2023-11-10 15;48;58](https://github.com/codeit-team8/rolling/assets/144667455/11ce5e8b-ca1f-4cfb-be31-27d028560fe9)

2023-11-10 07:03 UTC, hyeyoonS commented on src/components/Option/Option.jsx
> +  };
ColorChip과 ImageChip 컴포넌트를 객체로 한 곳에 담아서 만들어서 사용하고 싶었지만 사용하지 못했습니다 ,,

2023-11-10 07:05 UTC, hyeyoonS commented on src/components/Option/Option.jsx
> +    setIsActive((prev) => !prev);
이 코드가 있으면 같은 컬러칩을 두번 클릭하면 선택 아이콘이 사라질 것이라고 생각했지만 사라지지 않았습니다
그리고 이 코드가 없어도 정상 동작합니다 그렇다면 이 코드는 필요가 없는걸까요 ??

2023-11-10 07:06 UTC, gooma519 reviewed
저 오류는 스타일 컴포넌트에 props를 $달아서 내려주면 됩니다.

2023-11-10 07:07 UTC, hyeyoonS commented on src/components/Option/Option.jsx
> +function Option({ selectOption }) {
selectOption을 prop으로 내려주고 있어서, 컴포넌트를 사용하려면 Main에서   <Option selectOption={'backgroundColor'} /> 이런 식으로 받아와야 하는데요.. 이런 사용법이 맞는걸까요 ??

2023-11-10 07:11 UTC, gooma519 commented on src/components/Option/Option.jsx
> +function Option({ selectOption }) {
네 $selectOption 이렇게 이름 바꿔서 내려주시면 됩니다.

2023-11-10 07:45 UTC, kses1010 requested changes
고생하셨습니다. 몇군데만 고쳐주시면 될듯 합니다.
1. 전체적으로 px를 쓰셨어요 border, border-radius를 제외하고 가능하다면 rem으로 바꿔주세요.
2. 각 컴포넌트마다 한줄 개행을 넣어 보기 쉽게 해주셨으면 합니다.
3. 스타일 컴포넌트가 많아져 코드가 100~150줄 이상 넘어 갈경우 `컴포넌트.style.jsx`로 코드를 옮겨주세요.
4. 꼭 푸시 하기 전에 lint 돌리는거 잊지 말아주세요 lint 돌려서 어느곳이 코드스타일이 맞지 않는지 확인해주세요. lint 코드는 `npm run lint` 입니다.

2023-11-10 07:45 UTC, kses1010 commented on src/components/Option/Option.jsx
> +    'https://images.unsplash.com/photo-1699362232821-b2eccfc516e5?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
여기 이미지 swagger API에 호출해서 사용해서 그 링크를 가져오면 좀 더 짧게 나옵니다.

2023-11-10 07:45 UTC, kses1010 commented on src/components/Option/Option.jsx
> +    'https://images.unsplash.com/photo-1699362232821-b2eccfc516e5?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
이미지 URL은 따로 상수 파일로 빼서 사용하면 좋을듯 합니다.

2023-11-10 07:45 UTC, kses1010 commented on src/pages/Main.jsx
> +      <Option selectOption={'backgroundColor'} />
확인을 위한 컴퍼넌트니까 삭제부탁드려요~

2023-11-10 07:45 UTC, kses1010 commented on src/components/Option/Option.jsx
> +  };
어.. 어떻게 하고싶은건지 잘모르겠습니다. 구체적인 표현 부탁드려도 될까요?

2023-11-10 07:45 UTC, kses1010 commented on src/components/Option/Option.jsx
> +    setIsActive((prev) => !prev);
isActive를 사용하는 코드가 없어서 그렇습니당 isActive가 쓰이지 않는 코드라고 떠요 즉, isActive를 활용해서 렌더링하는 동작을 넣으면 해당 메서드가 돌아간답니다

2023-11-10 07:45 UTC, kses1010 commented on src/components/Option/Option.jsx
> +          </Button>
key를 해당 카테고리 이름으로 넣으시는걸 추천드립니다. 가능하다면 key에 index를 넣는 행위는 지양해주세용

2023-11-10 07:45 UTC, kses1010 commented on src/components/Option/Option.jsx
> +  // justify-content: center;
여기 한줄 개행 해주시고, 주석은 삭제해주세용

2023-11-10 07:45 UTC, kses1010 commented on src/components/Option/Option.jsx
> +const ColorChip = styled.div`
여기도 한줄 개행 부탁드려요

2023-11-10 07:45 UTC, kses1010 commented on src/components/Option/Option.jsx
> +  grid-template-rows: repeat(2, 154px);
가능하다면 grid로 배치할 때는 구체적 길이보다는 1fr, minmax를 활용부탁드립니당

2023-11-10 07:45 UTC, kses1010 commented on src/components/Option/Option.jsx
> +
여기 있는 버튼은 따로 styles 폴더로 옮겨도 될 듯 합니다.

2023-11-10 07:47 UTC, hyeyoonS commented
> 저 오류는 스타일 컴포넌트에 props를 $달아서 내려주면 됩니다.

$backgroundImageURL={imageURL} 코드를 이렇게 수정하면 이미지가 보이지 않습니다 ㅜㅜ

2023-11-10 07:52 UTC, hyeyoonS commented on src/components/Option/Option.jsx
> +function Option({ selectOption }) {
> 네 $selectOption 이렇게 이름 바꿔서 내려주시면 됩니다.

이 말씀을 이해를 잘 못하겠어서 혹시 조금 더 자세하게 설명 부탁드려도 될까요 ..!?!

2023-11-10 07:54 UTC, gooma519 commented on src/components/Option/Option.jsx
> +function Option({ selectOption }) {
https://www.notion.so/Part2-8-869417703ea54aa2b6970975fad09f00?p=e352964a54814c29a65c5b1b81db0d70&pm=s
여기에 설명 적어놓았습니다.

2023-11-10 08:33 UTC, kses1010 approved these changes
LGTM!

2023-11-10 08:33 UTC, BeMatthewsong commented on src/components/Option/Option.jsx
> +  };
객체를 한 곳에 담는 이유가 뭘까요? 제가 추측하기로는 가독성을 위해서 같습니다.

만약에 나누고 싶으면 선택하는 부분(4칸 그리드)을 컴포넌트로 분리해서 불러오는 방법 어떠신가요?

2023-11-10 08:45 UTC, hyeyoonS commented on src/components/Option/Option.jsx
> +function Option({ selectOption }) {
> https://www.notion.so/Part2-8-869417703ea54aa2b6970975fad09f00?p=e352964a54814c29a65c5b1b81db0d70&pm=s 여기에 설명 적어놓았습니다.

앗 혜지님 이부분은 혹시 맨 위에 올린 오류메시지에 대한 코멘트일까요 ?? $backgroundImageURL={imageURL} 코드를 이렇게 수정하면 이미지가 보이지 않습니다 ㅜㅜ,,,

2023-11-10 14:22 UTC, hyeyoonS commented on src/components/Option/Option.jsx
> +    'https://images.unsplash.com/photo-1699362232821-b2eccfc516e5?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
API문서에 있는 이미지 URL 가져와서 상수 파일로 분리했습니다!

2023-11-10 14:22 UTC, hyeyoonS commented on src/components/Option/Option.jsx
> +  };
민혁님이 말씀하신 내용이 맞습니다!!! 가독성을 위해서 컴포넌트로 분리해서 가져오고 싶었어요
[컬러버튼클릭→컬러칩 렌더링], [이미지 버튼 클릭→이미지렌더링] 이걸 코드로 표현하고 싶었는데 잘 안되었고
< isCategorySelect === 0 or 1 > 이렇게 표현하였습니다
그래서 이 부분은 사용되지 않는 부분이라 삭제하고 새로 푸쉬했습니다!

2023-11-10 14:22 UTC, hyeyoonS commented on src/components/Option/Option.jsx
> +          </Button>
key 값으로 index를 넣으면 안될 것 같으면서도 다른 방법을 잘 몰라 긴가민가하여 넣었던 부분입니다ㅠㅠ 혜지님이 상세하게 가이드 주셔서 key값에 카테고리 이름이 들어가도록 변경했습니다

2023-11-10 14:22 UTC, hyeyoonS commented on src/components/Option/Option.jsx
> +  // justify-content: center;
개행하고 사용하지 않는 속성은 삭제했습니다

2023-11-10 14:22 UTC, hyeyoonS commented on src/components/Option/Option.jsx
> +  grid-template-rows: repeat(2, 154px);
처음에 1fr을 사용하였으나 크기를 늘렸을 때 예쁘지 않게 가장자리에 딱 붙어버려서( 가장자리 여백이 늘어나고 가운데 gap은 고정되어야 하는데, 반대로 가운데 여백이 생기면서 늘어남) 수치로 고정한 부분입니다 ㅠㅠ

2023-11-10 14:22 UTC, hyeyoonS commented on src/components/Option/Option.jsx
> +const ColorChip = styled.div`
수정했습니다 !

2023-11-10 14:22 UTC, hyeyoonS commented on src/components/Option/Option.jsx
> +
분리했습니다 !

2023-11-10 14:22 UTC, hyeyoonS commented on src/pages/Main.jsx
> +      <Option selectOption={'backgroundColor'} />
삭제했습니다!

2023-11-10 14:25 UTC, hyeyoonS commented
> 고생하셨습니다. 몇군데만 고쳐주시면 될듯 합니다.
> 
> 1. 전체적으로 px를 쓰셨어요 border, border-radius를 제외하고 가능하다면 rem으로 바꿔주세요.
> 2. 각 컴포넌트마다 한줄 개행을 넣어 보기 쉽게 해주셨으면 합니다.
> 3. 스타일 컴포넌트가 많아져 코드가 100~150줄 이상 넘어 갈경우 `컴포넌트.style.jsx`로 코드를 옮겨주세요.
> 4. 꼭 푸시 하기 전에 lint 돌리는거 잊지 말아주세요 lint 돌려서 어느곳이 코드스타일이 맞지 않는지 확인해주세요. lint 코드는 `npm run lint` 입니다.

아 저 여태까지 lint를 안돌린 게 맞네요...  이번에 npm run lint를 해보았는데 잘 수정한 건지 모르겠습니다 ㅠㅠ 확인해보시구 미흡한 부분 있다면 가이드 부탁드립니다,,,, !!!

2023-11-10 14:49 UTC, gooma519 approved these changes
LGTM

2023-11-11 00:39 UTC, kses1010 approved these changes
한번 코드 봐주시면됩니다.

2023-11-11 00:39 UTC, kses1010 commented on src/assets/mock/mockBackgroundImg.jsx
> +const mockBackgroundImg = {
상수는 대문자로 써주세요

2023-11-11 00:39 UTC, kses1010 commented on src/components/Option/Option.style.jsx
> +  width: 12.2rem;
컴포넌트끼리 한줄 개행 부탁드립니다

2023-11-11 00:39 UTC, kses1010 commented on src/assets/mock/mockBackgroundImg.jsx
> +const mockBackgroundImg = {
MOCK_BACKGROUND_IMAGE

2023-11-11 00:39 UTC, kses1010 commented on src/components/Option/Option.jsx
> +  const [isActive, setIsActive] = useState(OPTIONS[selectOption][0]);
```suggestion
const [, setIsActive] = useState(OPTIONS[selectOption][0]);
```

2023-11-11 01:46 UTC, BeMatthewsong commented on src/components/Option/Option.style.jsx
> +      : `url(${$imageUrls})`};
이미지 칩만 컬러 칩과 다르게 선택하면 배경이 뿌옇게 되네요
피그마에서도 이렇게 되어있군요

2023-11-11 01:50 UTC, BeMatthewsong approved these changes
LGTM 고생하셨어요!

2023-11-11 01:53 UTC, hyeyoonS commented on src/assets/mock/mockBackgroundImg.jsx
> +const mockBackgroundImg = {
수정했습니다!

2023-11-11 01:53 UTC, hyeyoonS commented on src/components/Option/Option.style.jsx
> +      : `url(${$imageUrls})`};
네 컬러칩과 이미지칩을 분리한 이유도 이것때문입니다 ㅠ 피그마에는 light gray 50%  이렇게 표시되어있는데 코드잇 CSS강의에서 이미지 위에 linear-gradient를 사용하는 방법을 알려주었어서 그 방법으로 하였습니다! (혜지님이 도와주셨어욤)

2023-11-11 01:54 UTC, hyeyoonS commented on src/components/Option/Option.jsx
> +  const [isActive, setIsActive] = useState(OPTIONS[selectOption][0]);
[, setIsActive]  하니 잘 작동되어서 수정했습니다!!

2023-11-11 02:06 UTC, merged