[#53] fix : textInput initial value 수정
codeit-team8/rolling pull request #56
Opened 2023-11-11 00:54 UTC by gooma519

## #53 

## 구현 기능 및 변경 사항

- textInput 수정

## 스크린샷(선택)

2023-11-11 01:32 UTC, gooma519 reviewed
다음부터는 브랜치를 따로 빼서 진행하겠습니다!

2023-11-11 01:32 UTC, gooma519 commented on src/styles/input/TextInput.jsx
> +function TextInput({ setIsValidForm, getPostValue }) {
setIsValidForm으로 상위 컴포넌트(To, From페이지)의 유효성 검사를 하고, getPostValue로 post할 때 보내줄 data를 담습니다.

2023-11-11 01:38 UTC, BeMatthewsong approved these changes
LGTM! 잘만드셨네요

2023-11-11 04:37 UTC, kses1010 approved these changes
수정하느라 고생많으셨습니다. LGTM!

2023-11-11 04:37 UTC, kses1010 commented on src/pages/To.jsx
> +export default function To() {
가능하다
```suggestion
function To() {
...
}

export default To;
```
로 통일성있게 스타일을 정해주실 수 있을까요?

2023-11-11 04:37 UTC, kses1010 commented on src/styles/input/TextInput.jsx
> +    </div>
div를 추가하신 이유가 무엇인가요?

2023-11-11 06:53 UTC, gooma519 commented on src/styles/input/TextInput.jsx
> +    </div>
css 문제 때문에 넣어주었습니다.

2023-11-11 06:59 UTC, BeMatthewsong approved these changes
LGTM 깔끔하네요
막힐 때마다 혜지님 코드 보면 되겠네요

2023-11-11 06:59 UTC, BeMatthewsong commented on src/styles/input/TextInput.jsx
> +  width: 100%;
저도 너비 바꾸려고 했는데 머지하면 되겠네요~

2023-11-11 07:08 UTC, kses1010 reviewed
고생하셧습니다. 정말 많은걸 하셨네요 ㅎㄷㄷ

다만 API 세팅이 들어가서 저거 기준으로 다시 작업 부탁드려도 될까요?

2023-11-11 07:08 UTC, kses1010 commented on src/components/Option/Option.jsx
> +      setPostValue((prev) => ({ ...prev, backgroundColor: e.target.id, backgroundImageURL: null }));
`e.target.id`로 선택사항 이벤트의 요소를 가져올 수 있군요 좋네요!

2023-11-11 07:08 UTC, kses1010 commented on src/pages/To.jsx
> +  ${F.FONT16}
여기 `${스타일}`끝에 세미콜론 붙여주세용

2023-11-11 07:08 UTC, kses1010 commented on src/service/api.js
> +};
여기 부분은 제꺼 API 세팅 들어가면 교체하면 될듯 합니다

2023-11-11 07:08 UTC, kses1010 commented on src/styles/input/TextInput.jsx
> +  ${F.FONT16}
여기도 끝에 세미콜론 붙여주세요

2023-11-11 07:08 UTC, kses1010 commented on src/styles/input/TextInput.jsx
> +  ${F.FONT12}
여기도 마찬가지랍니다

2023-11-11 07:09 UTC, gooma519 commented on src/pages/To.jsx
> +  ${F.FONT16}
아이구 또 까먹었네요 죄송합니다ㅠㅠ

2023-11-11 07:10 UTC, gooma519 commented on src/service/api.js
> +};
넵 api 머지하고 다시 올리겠습니다.

2023-11-11 07:58 UTC, kses1010 approved these changes
네! 전부 확인했습니다 고생하셧습니당!

2023-11-11 08:09 UTC, hyeyoonS commented on src/pages/To.jsx
> +  }, []);
여기 왜 useCallback을 사용하셨는지 알 수 있을까요?? 한번만 불러오면 되는 거 아닌가요ㅠㅠ...?? 함수를 기억할 필요가 있나요?? 

const getBackImages = async () => {
    const { imageUrls } = await getBackgroundImages();
    setBackgroundImages(imageUrls);
  };

  useEffect(() => {
    getBackImages();
  }, []);

이렇게 하면 될거라고 생각하는데 아닌가요..!?! (궁금..... )

2023-11-13 01:10 UTC, kses1010 requested changes
고생하셨습니다. 
제가 RC 드리는 이유는 다름이 아니라 그 useAsync와 제가 만든 api를 사용하시기를 부탁드리고 싶었습니다. Comment를 읽어주시고 만약 이야기하고 싶은게 있으시면 말씀해주세요

2023-11-13 01:10 UTC, kses1010 commented on src/App.jsx
> +          <Route path=":postId/message" element={<FromPage />} />
고쳐주셨군요 감사합니다.

2023-11-13 01:10 UTC, kses1010 commented on src/components/Option/Option.jsx
> +];
저도 색깔 필요해서 style의 색깔 상수로 빼서 사용해볼 생각입니당

2023-11-13 01:10 UTC, kses1010 commented on src/components/Option/Option.jsx
> +  }, []);
백그라운드 이미지는 새로 생길일이 없으니 디펜던시에서 뺐군요!

2023-11-13 01:10 UTC, kses1010 commented on src/components/Option/Option.jsx
> +  }, []);
useAsync를 적용하여 loading, error를 한번에 관리하는 useState를 만드시는건 어떠세요?
```js
  const [getbackgroundImages, getBackgroundImagesError, getBackgroundImagesAsync] = useAsync(getBackgroundImages);
```

2023-11-13 01:10 UTC, kses1010 commented on src/pages/To.jsx
> +  );
여기서도 마찬가지로 useAsync를 활용해서 가져오도록 하면 좋을듯합니다.

2023-11-13 01:10 UTC, kses1010 commented on src/service/api.js
> +};
여기 코드는 사용하질 예정이니 삭제하시면됩니다.

2023-11-13 01:10 UTC, kses1010 commented on src/styles/input/TextInput.jsx
> +      setErrorMessage('이름은 2~20글자 이내로 특수문자는 포함하지  말아주세요.');
여기 띄어쓰기가 2칸? 3칸정도인데 1칸으로 줄여주세요

2023-11-13 01:10 UTC, kses1010 commented on src/styles/input/TextInput.jsx
> +  const [isValid, setIsValid] = useState(null);
이름은 is 변수라 불리언값같은데 null로 주신이유가 무엇인가요? 초기값은 false로 주어도 괜찮을것 같아요

2023-11-13 01:35 UTC, gooma519 commented on src/styles/input/TextInput.jsx
> +  const [isValid, setIsValid] = useState(null);
null이 아니라 false를 주게되면 초기에 아무것도 누르지 않았을 때도 error 상태가 되어버립니다.

2023-11-13 01:51 UTC, gooma519 commented on src/pages/To.jsx
> +  }, []);
저도 처음에는 그렇게 했는데 useEffect에 getBackImages를 넣어주라고 lint에 뜨더라구요

2023-11-13 02:18 UTC, kses1010 approved these changes
고생하셨습니다. LGTM!

2023-11-13 02:20 UTC, merged