[#65] 에러 화면
codeit-team8/rolling pull request #67
Opened 2023-11-13 07:24 UTC by gooma519

## #65 

## 구현 기능 및 변경 사항

- 에러화면 구현

## 스크린샷(선택)
![Nov-13-2023 16-18-01](https://github.com/codeit-team8/rolling/assets/144667600/647d0a34-a9c3-4342-98c6-730a088612dd)

2023-11-13 09:15 UTC, BeMatthewsong approved these changes
Look cute to me
잘만드셨네요 고생하셨습니다

2023-11-13 09:15 UTC, BeMatthewsong commented on package.json
> +    "react-error-boundary": "^4.0.11",
이건 어떤 라이브러리에요?!

2023-11-13 09:20 UTC, kses1010 requested changes
Router로 따로 처리하실줄 알았는데 놀라운 라이브러리군요 고생하셨습니다.

다만, 백그라운드 이미지 가져오는 url 테스트 하시고 커밋하셔서 고쳐야 하므로 RC 드려용

2023-11-13 09:20 UTC, kses1010 commented on package.json
> +    "react-error-boundary": "^4.0.11",
이게 에러 처리하는 라이브러리인가봅니다

2023-11-13 09:20 UTC, kses1010 commented on src/App.jsx
> +      <ErrorBoundary FallbackComponent={ErrorFallback}>
활용법이 되게 단순하네용

2023-11-13 09:20 UTC, kses1010 commented on src/api/backgroundImages.js
> +    const response = await axios.get(`${DOMAIN}/background-image/`);
여기 왜 image로 바꿨나요? 이러면 못가져와용

2023-11-13 09:20 UTC, kses1010 commented on src/hooks/useAsync.js
> +    [asyncFunction, showBoundary],
이렇게 해서 에러를 잡아 핸들링하는군요 되게 심플하네요

2023-11-14 01:15 UTC, kses1010 approved these changes
고생하셨습니다. LGTM!

2023-11-14 01:15 UTC, kses1010 commented on src/components/Option/Option.jsx
> +  const [, , getBackgroundImagesAsync] = useAsync(getBackgroundImages);
이렇게 되면 에러 state는 더이상 필요없게 되겠네요

2023-11-14 02:00 UTC, merged